# Init #
project: 'flow-model'
job_type: 'eval'
load_id: '2mlvusq5'

# Data #
data_module: 'OFDataModule'
case: '../../data/cylinder2D_base'
zones: ['internal','cylinder','inlet','outlet','top','bottom']
irreps_node: '6x0e'
num_nodes: 14000
dt: .01
ts: [3,6]
test_ts: [6,7.5]
rollout: 1
test_rollout: 150
# sample_graph: 'cluster'
# hops: 300
rc: [[.1,0,32], [.1,0,32], [.2,0,32]]

# # Model #
# num_levels: 3
# cf: [2, 2]
# skip_mp_levels_all: [[0,1],[0,2],[1,2],[1,2]]
# latent_layers: 4
# latent_scalars: 64
# latent_vectors: 64
# latent_tensors: 0
# model_type: 'equivariant'
# act: 'silu'
# solver: 'euler'
# sensitivity: 'autograd'
# reservoir: True

# # Training #
# data_aug: False
# batch_size: 2
# lr: 0.01
# lr_sch: True
# epochs: 100
# gpus: -1
# noise_fac: 0.5